apiVersion: apps/v1
kind: Deployment
metadata:
  name: Backend 
  labels:
    app: redis
    
spec: 
  replicas: 1
  selectors: 
    matchLabels:
       app: redis
       
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
          - containerPort: 6379